// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetserver.Data;

#nullable disable

namespace aspnetserver.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220409214727_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("aspnetserver.Data.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SellerID")
                        .HasMaxLength(9999)
                        .HasColumnType("INTEGER");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("itemPrice")
                        .HasMaxLength(9999)
                        .HasColumnType("INTEGER");

                    b.Property<int>("stock")
                        .HasMaxLength(9999)
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            Description = "This is post 1 and it has some very interesting content. I have also liked the video and subscribed.",
                            SellerID = 1000,
                            image = "URL",
                            itemName = "Post 1",
                            itemPrice = 10,
                            stock = 50
                        },
                        new
                        {
                            ItemID = 2,
                            Description = "This is post 2 and it has some very interesting content. I have also liked the video and subscribed.",
                            SellerID = 2000,
                            image = "URL",
                            itemName = "Post 2",
                            itemPrice = 20,
                            stock = 100
                        },
                        new
                        {
                            ItemID = 3,
                            Description = "This is post 3 and it has some very interesting content. I have also liked the video and subscribed.",
                            SellerID = 3000,
                            image = "URL",
                            itemName = "Post 3",
                            itemPrice = 30,
                            stock = 150
                        },
                        new
                        {
                            ItemID = 4,
                            Description = "This is post 4 and it has some very interesting content. I have also liked the video and subscribed.",
                            SellerID = 4000,
                            image = "URL",
                            itemName = "Post 4",
                            itemPrice = 40,
                            stock = 200
                        },
                        new
                        {
                            ItemID = 5,
                            Description = "This is post 5 and it has some very interesting content. I have also liked the video and subscribed.",
                            SellerID = 5000,
                            image = "URL",
                            itemName = "Post 5",
                            itemPrice = 50,
                            stock = 250
                        },
                        new
                        {
                            ItemID = 6,
                            Description = "This is post 6 and it has some very interesting content. I have also liked the video and subscribed.",
                            SellerID = 6000,
                            image = "URL",
                            itemName = "Post 6",
                            itemPrice = 60,
                            stock = 300
                        });
                });

            modelBuilder.Entity("aspnetserver.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
